# Generated by Django 4.2.11 on 2025-09-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0009_ingrediente_composicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='pesoAnvisa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tabela',
            name='acucaresadd_Mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
