# Generated by Django 4.2.11 on 2026-07-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_ficha_pesoanvisa_alter_tabela_acucaresadd_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha_ingrediente',
            name='quantidadeMedidaCaseira',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
