# Generated by Django 4.2.11 on 2026-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0011_ficha_ingrediente_quantidademedidacaseira'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='quantidadeMedCaseiraPorcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
