# Generated by Django 4.2.11 on 2026-07-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0012_ficha_quantidademedcaseiraporcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_ingrediente',
            name='quantidadeMedidaCaseira',
        ),
    ]
