# Generated by Django 2.1.7 on 2020-01-15 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='dataCriacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='dataCriacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
