# Generated by Django 2.1.7 on 2020-04-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0004_remove_membro_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='medCaseiraPorcao',
            field=models.CharField(default='medida caseira', max_length=120),
        ),
    ]
