# Generated by Django 2.1.7 on 2023-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_ficha_medcaseiraporcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='acidoFolico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='acidoFolico_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='acidoPantotenico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='acidoPantotenico_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='acucaresadd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='acucaresadd_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='biotina',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='biotina_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cloreto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cloreto_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='colina',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='colina_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cromo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='cromo_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='fluor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='fluor_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='iodo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='iodo_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='molibdenio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='molibdenio_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='omega3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='omega3_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='omega6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='omega6_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='selenio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='selenio_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaB12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaB12_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaD_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaE_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaK',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='vitaminaK_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='agitcidoFolico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoFolico_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoFolico_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoFolico_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoFolico_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoFolico_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoFolico_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acidoPantotenico_unidadeMd',
            field=models.CharField(default='mg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresadd_unidadeMd',
            field=models.CharField(default='g', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='biotina_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cloreto_unidadeMd',
            field=models.CharField(default='mg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='colina_unidadeMd',
            field=models.CharField(default='mg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='cromo_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='fluor_unidadeMd',
            field=models.CharField(default='mg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='iodo_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='molibdenio_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega3_unidadeMd',
            field=models.CharField(default='mg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='omega6_unidadeMd',
            field=models.CharField(default='g', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='selenio_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaB12_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaD_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaE_unidadeMd',
            field=models.CharField(default='mg', max_length=5),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK_Mostrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='vitaminaK_unidadeMd',
            field=models.CharField(default='μg', max_length=5),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='medCaseiraPorcao',
            field=models.CharField(blank=True, default='medida caseira', max_length=120),
        ),
        migrations.AlterField(
            model_name='ficha_ingrediente',
            name='medidaCaseira',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
