# Generated by Django 2.1.7 on 2020-02-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_auto_20200115_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nomeFicha',
            field=models.CharField(max_length=500),
        ),
    ]
