# Generated by Django 2.1.7 on 2020-03-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20200211_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='senha',
        ),
    ]
