# Generated by Django 5.0.3 on 2024-03-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0006_auto_20230416_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabela',
            old_name='agitcidoFolico',
            new_name='acidoFolico',
        ),
    ]
