# Generated by Django 5.0.4 on 2024-11-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_rename_agitcidofolico_tabela_acidofolico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='acucaresTotais',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='acucaresTotais_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais_100g',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais_Arred',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais_Mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais_Porcao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais_VD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tabela',
            name='acucaresTotais_unidadeMd',
            field=models.CharField(default='g', max_length=5),
        ),
    ]
