# Generated by Django 4.2.11 on 2025-08-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_ingrediente_acucarestotais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='composicao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
